# Generated by Django 5.2.15 on 2026-06-05 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_location'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('product', 'Product'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated required skills'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', '-created_at'], name='jobs_job_is_feat_e3be6a_idx'),
        ),
    ]
