# Generated by Django 5.2.15 on 2026-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
